TW_THEME := portrait_hdpi
BOARD_HAS_FLIPPED_SCREEN := true
RECOVERY_GRAPHICS_USE_LINELENGTH := true
TW_BRIGHTNESS_PATH := /sys/class/backlight/pwm-backlight/brightness
TW_MAX_BRIGHTNESS := 255
TW_USE_TOOLBOX := true
TW_EXCLUDE_SUPERSU := true
RECOVERY_SDCARD_ON_DATA := true
TW_DEVICE_VERSION := raphaelcfrajuca
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
TW_DEFAULT_BRIGHTNESS := 162
TW_INCLUDE_CRYPTO := true
TW_MTP_DEVICE := "/dev/mtp_usb"

# Touchscreen support
TARGET_RECOVERY_DEVICE_MODULES := rm-wrapper
